<?php echo Tag::css("comun") ?>
<?php echo Tag::js("comun") ?>
<div class="container">
	<div class="text-center"><h2>Lista de Usuarios</h2></div>
	<?php View::content() ?>
	<?php echo Html::link("usuario/register","<span class='glyphicon glyphicon-plus'></span>","title='Nuevo Usuario' class='btn btn-success btn-xs'") ?>
	<br>
	<br>
	<table class="table">
		<thead>
			<th>Email</th>
			<th>Nombre y Apellido</th>
			<th>Dni</th>
			<th>Tlf.</th>
			<th>Direc.</th>
			<th></th>
		</thead>
		<?php foreach ($usuarios as $key => $value): ?>
			<tr>
				<td><?php echo $value->email ?></td>
				<td><?php echo $value->nombre." ".$value->apellido ?></td>
				<td><?php echo $value->dni ?></td>
				<td><?php echo $value->telefono ?></td>
				<td><p><?php echo $value->direccion ?></p></td>
				<td>
					<div class="btn-group btn-group-xs" role="group" aria-label="">
					  <a href="<?php echo PUBLIC_PATH.'usuario/eliminar/'.$value->id ?>" message="Estas seguro de Eliminar al usuario?" title="Eliminar" class="btn btn-danger eliminar"><span class="glyphicon glyphicon-remove"></span></a>
					  
					  <a href="<?php echo PUBLIC_PATH.'usuario/editar/'.$value->id ?>" title="Editar" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>

					</div>
				</td>
			</tr>
		<?php endforeach ?>
	</table>
</div>