<?php echo Tag::css("comun") ?>
<div class="container">
  <?php View::content() ?>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#misdatos" aria-controls="misdatos" role="tab" data-toggle="tab">Mis datos</a></li>
    <li role="presentation"><a href="#findesemana" aria-controls="findesemana" role="tab" data-toggle="tab">Fin de semana</a></li>
    <li role="presentation"><a href="#eventos" aria-controls="eventos" role="tab" data-toggle="tab">Eventos</a></li>
    <li role="presentation"><a href="#comidas" aria-controls="comidas" role="tab" data-toggle="tab">Comidas</a></li>
    <li role="presentation"><a href="#contacto" aria-controls="contacto" role="tab" data-toggle="tab">Contacto</a></li>
  </ul>
<style type="text/css">
  table th{
    width:350px;
  }
</style>
  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="misdatos">
      <h1 class="text-center">Mis Datos</h1>
      <div class="text-center cargando hide">
        <center>Cargando...</center>
        <?php echo Html::img("spin.gif","Cargando") ?>
        <br>
        <br>
      </div>
      <div class="mensajes_mis_tados"></div>
      <table class="table table-bordered table-striped">
        <thead>
          <th><b>Nombre</b></th>
          <td><?php echo $usuario->nombre." ".$usuario->apellido ?></td>
        </thead>
        <thead>
          <th><b>DNI</b></th>
          <td><?php echo $usuario->dni ?></td>
        </thead>
        <thead>
          <th><b>Tipo de Usuario</b></th>
          <td><?php echo $usuario->tipo_usuario ?></td>
        </thead>
        <thead>
          <th><b>Compañia</b></th>
          <td><?php echo $usuario->compania ?></td>
        </thead>
        <thead>
          <th><b>Sección</b></th>
          <td><?php echo $usuario->seccion ?></td>
        </thead>
        <thead>
          <th><b>Teléfono</b></th>
          <td class="input-group"><input type="text" value="<?php echo $usuario->telefono ?>" class="form-control"><span class="input-group-btn"><button class="btn btn-default" id="actualizar_telefono" usuario="<?php echo $usuario->id ?>" type="button">Actualizar</button></span></td>
        </thead>
        <thead>
          <th><b>Email</b></th>
          <td><?php echo $usuario->email ?></td>
        </thead>
        <thead>
          <th><b>Dirección</b></th>
          <td class="input-group"><input type="text" class='form-control' value="<?php echo $usuario->direccion ?>"><span class="input-group-btn"><button class="btn btn-default" id="actualizar_direccion" usuario="<?php echo $usuario->id ?>" type="button">Actualizar</button></span></td>
        </thead>
        <thead>
          <th><b>Contraseña</b></th>
          <td>        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
          Cambiar Contraseña
        </button></td>
        </thead>
      </table>
    </div>

    <div role="tabpanel" class="tab-pane" id="findesemana">
      <h1 class="text-center">Fin de Semana</h1>
      <div id="mensajes_fines"></div>
      <?php echo Form::open("fines/registrar","post","id='form_fines'") ?>
      <div class="check">
        <label>
          <input type="checkbox" name="fines[se_queda]" id="se_queda" checked> Me quedo esta fin de semana
        </label>
      </div>
   
      <div class="form-group hide">
        <label>Dirección</label>
        <?php echo Form::hidden("fines.usuario_id",NULL,$usuario->id) ?>
        <?php echo Form::textarea("fines.direccion","class='form-control' placeholder='Indique la dirección aqui...'") ?>
      </div>
      <?php echo Form::hidden("fines.fecha_inicio",NULL,date("Y-m-d H:i:s", strtotime('next Saturday'))) ?>
      <?php echo Form::hidden("fines.fecha_final",NULL,date("Y-m-d H:i:s", strtotime('next Sunday'))) ?>
      <div class="text-center">
        <?php echo Form::submit("Registrar","class='btn btn-default'") ?>
  
        <!-- Button trigger modal -->
<button type="button" class="btn btn-default" data-toggle="modal" data-target="#my_weekend">
  Fines de Semana
</button>


      </div>
      <?php echo Form::close() ?>
    </div>
    <div role="tabpanel" class="tab-pane" id="eventos">
      <h1 class="text-center">Eventos</h1>
    
    </div>
    <div role="tabpanel" class="tab-pane" id="comidas">
      <h1 class="text-center">Comidas</h1>

    </div>
    <div role="tabpanel" class="tab-pane" id="contacto">
      <h1 class="text-center">Contacto</h1>

    </div>
  </div>

</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Cambiar Contraseña</h4>
      </div>
      <div class="modal-body">
        <div class="mensajes"></div>
        <?php echo Form::open("usuario/cambiopass","post","id='cambio_contrasena'") ?>
        <?php echo Form::hidden("usuario.id") ?>
        <div class="form-group">
          <label>Contraseña</label>
          <?php echo Form::pass("contrasena","class='form-control'") ?>
        </div>
        <div class="form-group">
          <label>Repetir Contraseña</label>
          <?php echo Form::pass("contrasena2","class='form-control'") ?>
        </div>
        <?php echo Form::close() ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" id="btn_contrasena">Guardar Cambios</button>
      </div>
    </div>
  </div>
</div>
<!-- Modal my_weekend-->
<div class="modal fade" id="my_weekend" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Mis fines de semana registrados</h4>
      </div>
      <div class="modal-body">
        <div class="tabla_fines">
          <?php if ($fines): ?>
            <?php echo $fines ?>
          <?php endif ?>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      
      </div>
    </div>
  </div>
</div>
<link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>datatables/css/jdataTables.bootstrap.min.css">
<link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>datatables/css/jquery.dataTables.min.css">
<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>datatables/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>datatables/js/dataTables.bootstrap.min.js"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $("body").on("click","#actualizar_direccion,#actualizar_telefono",function(){
      var accion = $(this).attr("id").split("_")[1];
      var id = $(this).attr("usuario");
      $(".cargando").removeClass("hide");
      $.ajax({
        url:"editar_valor/"+accion+"/"+id+"/"+$(this).parent().parent().find("input[type='text']").val(),
        dataType:"json",
        success:function(r){
          $(".cargando").addClass("hide");

          $(".mensajes_mis_tados").html("<div class='alert alert-info'>"+'<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+r.message+"</div>");
        }
      })
    });
    $("body").on("click","#btn_contrasena",function(){
      var url = $(this).attr("action");
      $.ajax({
        url:"cambiopass",
        type:"POST",
        data:$("#cambio_contrasena").serialize(),
        dataType:"json",
        success:function(r){
          $(".mensajes").html("<div class='alert alert-info'>"+'<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+r.message+"</div>");
        }
      })
      return false;
    })
    $("body").on("click","#se_queda",function(){
      if ($(this).is(":checked") == true) {
        $(this).parent().parent().parent().find(".form-group").addClass("hide")
      }else{
        $(this).parent().parent().parent().find(".form-group").removeClass("hide")

      }
    });
    $("body").on("submit","#form_fines",function(){
      $.ajax({
        url:$(this).attr("action"),
        data:$(this).serialize(),
        type:"post",
        dataType:"json",
        success:function(r){
          if (r.success ==  true) {
            $(".tabla_fines").html(r.registros);
          }
          $("#mensajes_fines").html("<div class='alert alert-info'>"+r.message+"</div>");
        }
      })
      return false;
    })
    $(".datatables").DataTable({
      language:{
          "sProcessing":     "Procesando...",
          "sLengthMenu":     "Mostrar _MENU_ registros",
          "sZeroRecords":    "No se encontraron resultados",
          "sEmptyTable":     "Ningún dato disponible en esta tabla",
          "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
          "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
          "sInfoPostFix":    "",
          "sSearch":         "Buscar:",
          "sUrl":            "",
          "sInfoThousands":  ",",
          "sLoadingRecords": "Cargando...",
          "oPaginate": {
              "sFirst":    "Primero",
              "sLast":     "Último",
              "sNext":     "Siguiente",
              "sPrevious": "Anterior"
          },
          "oAria": {
              "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
              "sSortDescending": ": Activar para ordenar la columna de manera descendente"
          }
      }
    });
  });
</script>