<style type="text/css">
@import url(http://fonts.googleapis.com/css?family=Roboto);
	body{
		background: grey;
	}
	.container{
		background: #f7f7f7;
		padding: 30px;
	    left: 50%;
	    top: 50%;
	    position: absolute;

	    -webkit-transform: translate3d(-50%, -50%, 0);
	    -moz-transform: translate3d(-50%, -50%, 0);
	    transform: translate3d(-50%, -50%, 0);
	}
.loginmodal-container {
  padding: 30px;
  max-width: 500px;
  width: 100% !important;
  background-color: #F7F7F7;
  margin: 0 auto;
  border-radius: 2px;
  box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
  overflow: hidden;
  font-family: roboto;
}

.loginmodal-container h1 {
  text-align: center;
  font-size: 1.8em;
  font-family: roboto;
}

.loginmodal-container input[type=submit] {
  width: 100%;
  display: block;
  margin-bottom: 10px;
  position: relative;
}

.loginmodal-container input[type=text], input[type=password],input[type=textarea],select {
  height: 44px;
  font-size: 16px;
  width: 100%;
  margin-bottom: 10px;
  -webkit-appearance: none;
  background: #fff;
  border: 1px solid #d9d9d9;
  border-top: 1px solid #c0c0c0;
  /* border-radius: 2px; */
  padding: 0 8px;
  box-sizing: border-box;
  -moz-box-sizing: border-box;
}

.loginmodal-container input[type=text]:hover, input[type=password]:hover,select {
  border: 1px solid #b9b9b9;
  border-top: 1px solid #a0a0a0;
  -moz-box-shadow: inset 0 1px 2px rgba(0,0,0,0.1);
  -webkit-box-shadow: inset 0 1px 2px rgba(0,0,0,0.1);
  box-shadow: inset 0 1px 2px rgba(0,0,0,0.1);
}

.loginmodal {
  text-align: center;
  font-size: 14px;
  font-family: 'Arial', sans-serif;
  font-weight: 700;
  height: 36px;
  padding: 0 8px;
/* border-radius: 3px; */
/* -webkit-user-select: none;
  user-select: none; */
}

.loginmodal-submit {
  /* border: 1px solid #3079ed; */
  border: 0px;
  color: #fff;
  text-shadow: 0 1px rgba(0,0,0,0.1); 
  background-color: #4d90fe;
  padding: 17px 0px;
  font-family: roboto;
  font-size: 14px;
  /* background-image: -webkit-gradient(linear, 0 0, 0 100%,   from(#4d90fe), to(#4787ed)); */
}

.loginmodal-submit:hover {
  /* border: 1px solid #2f5bb7; */
  border: 0px;
  text-shadow: 0 1px rgba(0,0,0,0.3);
  background-color: #357ae8;
  /* background-image: -webkit-gradient(linear, 0 0, 0 100%,   from(#4d90fe), to(#357ae8)); */
}

.loginmodal-container a {
  text-decoration: none;
  color: #666;
  font-weight: 400;
  text-align: center;
  display: inline-block;
  opacity: 0.6;

  transition: opacity ease 0.5s;
} 

.login-help{
  font-size: 12px;
}
#form_login {
    left: 50%;
    top: 50%;
    position: absolute;
    -webkit-transform: translate3d(-50%, -50%, 0);
    -moz-transform: translate3d(-50%, -50%, 0);
    transform: translate3d(-50%, -50%, 0);
}
</style>
<div class="container loginmodal-container">
	<?php if (Auth::is_valid()): ?>
	<!-- Esto lo hice porque cuando el usuario esta logueado se monta el navbar con el form-->
		<br><br>
	<?php endif ?>
		<h1>Formulario de Registro</h1><br>
		<?php View::content() ?>
	<?php echo Form::open() ?>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label>Email</label>
				<?php echo Form::text("usuario.email","class='form-control' placeholder='E-mail'") ?>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group">
				<label>Dni</label>
				<?php echo Form::text("usuario.dni","class='form-control' placeholder='DNI'") ?>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label>Nombres</label>
				<?php echo Form::text("usuario.nombre","class='form-control' placeholder='Nombres'") ?>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group">
				<label>Apellidos</label>
				<?php echo Form::text("usuario.apellido","class='form-control' placeholder='Apellidos'") ?>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label>Tipo de Usuario</label>
				<?php if (Auth::is_valid()): ?>
					<?php if (Auth::get("tipo_usuario") == "ADMINISTRADOR"): ?>
						<?php $tipos = array(""=>"SELECCIONE","ALUMNO"=>"ALUMNO","PROFESOR"=>"PROFESOR","ADMINISTRADOR"=>"ADMINISTRADOR") ?>
					<?php elseif(Auth::get("tipo_usuario") == "PROFESOR"): ?>
						<?php $tipos = array(""=>"SELECCIONE","ALUMNO"=>"ALUMNO") ?>
					<?php else: ?>
						<?php $tipos = array(""=>"SELECCIONE") ?>
					<?php endif ?>
				<?php else: ?>
					<?php $tipos = array(""=>"SELECCIONE") ?>
				<?php endif ?>
				<?php echo Form::select("usuario.tipo_usuario",$tipos,"class='form-control' required") ?>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group">
				<label>Compañia</label>
				<?php echo Form::text("usuario.compania","class='form-control' placeholder='Compañia'") ?>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label>Sección</label>
				<?php echo Form::text("usuario.seccion","class='form-control' placeholder='Sección'") ?>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group">
				<label>Teléfono</label>
				<?php echo Form::text("usuario.telefono","class='form-control' placeholder='Teléfono'") ?>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<label>Dirección</label>
			<?php echo Form::textarea("usuario.direccion","class='form-control' placeholder='Dirección'") ?>
		</div>

	</div>
	<br>
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<label>Contraseña</label>
				<?php echo Form::pass("usuario.contrasena","class='form-control' placeholder='Contraseña'") ?>
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group">
				<label>Repetir Contraseña</label>
				<?php echo Form::pass("usuario.contrasena2","class='form-control' placeholder='Repetir Contraseña'") ?>
			</div>
		</div>
	</div>
	<br>
	<input type="submit" name="register" class="login loginmodal-submit" value="REGISTRO">
	  <div class="login-help">
		<a href="<?php echo PUBLIC_PATH ?>index/login">Login</a>
		<?php if (Auth::is_valid() and Auth::get("tipo_usuario") == "ADMINISTRADOR"): ?>
			- <a href="<?php echo PUBLIC_PATH ?>usuario/">Lista de Usuarios</a>
		<?php endif ?>
	  </div>
	<?php echo Form::close() ?>
</div>