
 


    
     
             <div class="container well">
<p>El index seria una pagina solo con el logging y que pueda entrar como alumno, como profesor o como administrador.

<p><b>Como alumno:</b></p>
<p>En la cabecera que ponga bienvenido y el nombre del alumno y en la esquina superior derecha cerrar sesión y que vuelva al index.</p>
<p><b>Pestañas:</b></p>
<p>Mis datos, fin de semana, eventos, comidas y contacto.</p>
<p>En pestaña mis datos tiene que tener un formulario con los datos apellidos, nombre, dni, tipo de usuario, compañía, sección, teléfono, dirección y contraseña.</p>
<p>Y que permita modificarse los datos de dirección, teléfono y contraseña.</p>
<p>En la pestaña fines de semana habrá un formulario con las siguientes preguntas,</p>
<p>Si se queda o no el fin de semana y la dirección donde se ira, siempre por defecto como que no se ira cuando no se apunte.</p>
<p>En la pestaña de eventos aparecerán los eventos que creen los profesores o administradores y un botón para ver detalles del evento y dentro de este para apuntarse o no al evento, también por defecto que sea que no.</p>
<p>En la pestaña de comidas saldrá un formulario con desayuno comidas y cenas de todos los días de la semana y el usuario se apuntara a la comida que quiera y por defecto siempre no.</p>
<p>En todas esas pestañas siempre se renovaran los eventos por semanas automáticamente menos la de eventos que se actualizara siempre que se ponga uno nuevo o expiren los antiguos.</p>
<p>En la pestaña de contacto será un formulario con un cuadro de texto para ponerse en contacto con un administrador al que le llegara la información al correo.</p>

<p><b>Como profesor:</b></p>
<p>En usuarios tendrá un botón para crear nuevos usuarios (no podrá crear profesores ni administradores), también podrá modificar toda la información de los usuarios.
En eventos, comidas y eventos podrán generar listas en pdf con la gente que este apuntada como que si asistirá y con la gente que puso que no.
Podrá también crear eventos.</p>

<p>
<p> <b> Como administrador:</b></p>
Tendrá control total para crear todo tipo de usuarios (profesores y administradores también) y de modificar todos los datos.
Podrá crear eventos, editarlos o borrarlos y generar listas de los eventos, fines de semana y comidas.
</p>
    </div>
