<link href='<?php echo PUBLIC_PATH ?>javascript/fullcalendar-2.9.0/fullcalendar.css' rel='stylesheet' />
<link href='<?php echo PUBLIC_PATH ?>javascript/fullcalendar-2.9.0/fullcalendar.print.css' rel='stylesheet' media='print' />
<script src='<?php echo PUBLIC_PATH ?>javascript/fullcalendar-2.9.0/lib/moment.min.js'></script>
<script src='<?php echo PUBLIC_PATH ?>javascript/fullcalendar-2.9.0/lib/jquery.min.js'></script>
<script src='<?php echo PUBLIC_PATH ?>javascript/fullcalendar-2.9.0/fullcalendar.min.js'></script>
<script type="text/javascript">
  $(document).ready(function(){
    $("#calendar").fullCalendar();
  });
</script>
<div  style="width:50%;margin:auto">

  <div id="calendar"></div>
</div>