<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    <?php if (isset($title)): ?>
      <?php echo "Gestión de Eventos/".$title ?>
    <?php else: ?>
      <?php echo "Gestión de Eventos/" ?>
    <?php endif ?>
  </title>
  <!--<?php //Tag::css('bienvenida') ?>
  <?php //Tag::css('style') ?>-->
  <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>bootstrap/css/bootstrap.min.css">
  <?php echo Tag::css("dashboard") ?>
  <?php echo Tag::js("jquery/jquery.min") ?>
  <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>bootstrap/js/bootstrap.min.js"></script>
  <?php echo Html::includeCss() ?>
      <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id='content'>
        <?php if(Auth::is_valid()): ?>
            <nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container-fluid">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo PUBLIC_PATH ?>usuario/panel"><?php echo $project_name ?></a>
                  </div>
                  <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                      <li class="dropdown">

                          <a href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo Auth::get("nombre")." ".Auth::get("apellido") ?> <b class="caret"></b></a>

                          <ul class="dropdown-menu">

                             

                              <!--<li><a href="#">Drafts</a></li>

                              <li><a href="#">Sent Items</a></li>

                              <li class="divider"></li>-->

                              <li><a href="<?php echo PUBLIC_PATH ?>usuario/logout">Cerrar Sesión</a></li>

                          </ul>

                      </li>
                      <?php if (Auth::is_valid() and Auth::get("tipo_usuario") == "ADMINISTRADOR"): ?>
                      <li class="dropdown">

                          <a href="#" data-toggle="dropdown" class="dropdown-toggle">Administración <b class="caret"></b></a>

                          <ul class="dropdown-menu">

                              <li><a href="<?php echo PUBLIC_PATH ?>usuario/">Módulo Usuarios</a></li>

                              <li><a href="<?php echo PUBLIC_PATH ?>fines/">Módulo Fines de Semana</a></li>

                              <li><a href="<?php echo PUBLIC_PATH ?>evento/">Módulo de Eventos</a></li>
                              <li><a href="<?php echo PUBLIC_PATH ?>comidas/">Módulo de Comidas</a></li>
                              <li><a href="<?php echo PUBLIC_PATH ?>contacto/">Módulo de Contacto</a></li>
                           

                          </ul>

                      </li>
                      <?php elseif(Auth::is_valid() and Auth::get("tipo_usuario") == "PROFESOR"): ?>
                      <li class="dropdown">
                          <a href="#" data-toggle="dropdown" class="dropdown-toggle">Profesor <b class="caret"></b></a>

                          <ul class="dropdown-menu">

                              <li><a href="<?php echo PUBLIC_PATH ?>usuario/">Módulo Usuarios</a></li>

                              <!--<li><a href="<?php //echo PUBLIC_PATH ?>fines/">Módulo Fines de Semana</a></li>-->

                              <li><a href="<?php echo PUBLIC_PATH ?>evento/">Módulo de Eventos</a></li>
                              <li><a href="<?php echo PUBLIC_PATH ?>comidas/">Módulo de Comidas</a></li>
                           

                          </ul>   
                        </li>                   
                      <?php endif ?>
                    </ul>
                    <!--<form class="navbar-form navbar-right">
                      <input type="text" class="form-control" placeholder="Search...">
                    </form>-->
                  </div>
                </div>
              </nav>

        <?php endif;?>
        <div class="container-fluid">
             <div class="row">
            <?php View::content(); ?>
             </div>
        </div>
    </div>
</body>
</html>
