<?php echo Tag::css("comun") ?>
<?php echo Tag::js("comun") ?>
<link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>datatables/css/dataTables.bootstrap.min.css">
<!--<link rel="stylesheet" href="<?php// echo PUBLIC_PATH ?>datatables/css/jquery.dataTables.min.css">-->
<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>datatables/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>datatables/js/dataTables.bootstrap.min.js"></script>
<div class="container">
	<div class="text-center">
		<h2>Mensajes</h2>
	</div>
	<?php View::content() ?>
	<table class="table datatables">
		<thead>
			<th>Usuario</th>
			<th style="width:200px">Titulo</th>
			<th>Mensaje</th>
			<th>Fecha</th>
			<th></th>
		</thead>
		<?php foreach ($mensajes as $key => $value): ?>
			<tr>
				<td><?php echo $value->usuario ?></td>
				<td><?php echo $value->titulo ?></td>
				<td><?php echo Util::recortar_texto($value->mensaje,50).'<button type="button" class="btn btn-link" data-toggle="modal" data-target="#'.$value->id.'">
				  [Ver más...]
				</button>' ?>
				</td>
				<td><?php echo $value->fecha_registro ?></td>
				<td>
					<div class="btn-group btn-group-xs" role="group" aria-label="">
					  <a href="<?php echo PUBLIC_PATH.'contacto/eliminar/'.$value->id ?>" message="Estas seguro de Eliminar este mensaje?" title="Eliminar" class="btn btn-danger eliminar"><span class="glyphicon glyphicon-remove"></span></a>
			

					</div>
				</td>
			</tr>
		<?php endforeach ?>
	</table>
</div>
<script type="text/javascript">
	$(document).ready(function(){
	    $(".datatables").DataTable({
	    	"iDisplayLength": 5,
	      language:{
	          "sProcessing":     "Procesando...",
	          "sLengthMenu":     "Mostrar _MENU_ registros",
	          "sZeroRecords":    "No se encontraron resultados",
	          "sEmptyTable":     "Ningún dato disponible en esta tabla",
	          "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
	          "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
	          "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
	          "sInfoPostFix":    "",
	          "sSearch":         "Buscar:",
	          "sUrl":            "",
	          "sInfoThousands":  ",",
	          "sLoadingRecords": "Cargando...",
	          "oPaginate": {
	              "sFirst":    "Primero",
	              "sLast":     "Último",
	              "sNext":     "Siguiente",
	              "sPrevious": "Anterior"
	          },
	          "oAria": {
	              "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
	              "sSortDescending": ": Activar para ordenar la columna de manera descendente"
	          }
	      }
	    });

	})
</script>

		<?php foreach ($mensajes as $key => $value): ?>
<div class="modal fade" id="<?php echo $value->id ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><?php echo $value->titulo ?></h4>
      </div>
      <div class="modal-body">
<p>
	<?php echo $value->mensaje ?>
</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>

      </div>
    </div>
  </div>
</div>
		<?php endforeach ?>